In [2]:
import numpy as np

In [3]:
vec = np.linspace(0, 11, 10)
print(vec)

[ 0.          1.22222222  2.44444444  3.66666667  4.88888889  6.11111111
  7.33333333  8.55555556  9.77777778 11.        ]

In [4]:
np.random.random((3,3))

array([[0.11505021, 0.54010281, 0.19241755],
       [0.90639868, 0.0850919 , 0.57781993],
       [0.26250417, 0.94742989, 0.67285639]])

In [5]:
np.random.randint(0,11,(5,5))

array([[ 4,  9,  5,  6,  0],
       [ 5,  5,  6,  8,  0],
       [ 8,  1,  2,  4,  2],
       [10,  8,  5, 10,  2],
       [ 9,  4,  2,  7,  5]], dtype=int32)

In [6]:
mat_1 = np.ones((3,4))
mat_2 = np.zeros((5,3))
np.savez('test_np.npz',ones_mat = mat_1 ,zeros_mat = mat_2)

In [7]:
with np.load('test_np.npz') as file:
    mat1= file['ones_mat']
    mat2= file['zeros_mat']

In [8]:
print(mat2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [9]:
m1 = np.array([[1,2,3],
              [4,5,6]])

m2 = np.array([[7,8,9],
              [0,0,0]])

In [10]:
mat_s = np.hstack((m1, m2))
print(mat_s)

[[1 2 3 7 8 9]
 [4 5 6 0 0 0]]

In [11]:
s = 4
v = np.array([2,4,3,4,10])
v == s

array([False,  True, False,  True, False])

In [12]:
v1 = np.array([2,4,3,4,5])
v2 = np.array([2,4,3,4,10])
v1 ==v2

array([ True,  True,  True,  True, False])

In [13]:
v1 =np.array([0,4,3,4,5])
np.all(v1>=1)

np.False_

In [14]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])

np.isclose(v1, v2, atol=1)

array([ True,  True, False,  True, False])

In [15]:
np.allclose(v1, v2, atol=1)

False

In [16]:
v = np.array([2,4,3,4,10])
condition = v>= 4
print(condition)

new_arr =np.where(condition, -1,v)
print(new_arr)

[False  True False  True  True]
[ 2 -1  3 -1 -1]

In [17]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\hashe\appdata\local\programs\python\python312\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hashe\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hashe\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hashe\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\hashe\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
import pandas as pd

In [19]:
df = pd.read_csv('test.csv')
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011

In [20]:
df.tail()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
35,36,KHOA TRINH,ELECTRONIC MAINTENANCE TECHNICIAN,101953.20,139102.95,16483.94,NaN,257540.09,257540.09,2011
36,37,SUSAN CURRIN,"ADMINISTRATOR, SFGH MEDICAL CENTER",245124.44,0.00,12000.00,NaN,257124.44,257124.44,2011
37,38,JAMES BOSCH,"INSPECTOR III, (POLICE DEPARTMENT)",110661.20,31162.04,111446.20,NaN,253269.44,253269.44,2011
38,39,JONES WONG,LIEUTENANT III (POLICE DEPARTMENT),132202.26,52648.92,67083.83,NaN,251935.01,251935.01,2011
39,40,BRENDAN WARD,"BATTALION CHIEF, (FIRE DEPARTMENT)",147158.85,64985.85,39540.46,NaN,251685.16,251685.16,2011

In [21]:
s = pd.Series([1,2,3,4],index=['A','B','C','D'])
s

A    1
B    2
C    3
D    4
dtype: int64

In [22]:
data = [[1,444,'abc'],
        [1,555,'def'],
        [3,666,'ghi'],
        [4,777,'xyz']
        ]
df =pd.DataFrame(data,columns=["idx","id","name"])
display(df)

   idx   id name
0    1  444  abc
1    1  555  def
2    3  666  ghi
3    4  777  xyz

In [23]:
df['id'].dtypes

dtype('int64')

In [24]:
df['id'] = df['id'].astype("category")
df.dtypes

idx        int64
id      category
name         str
dtype: object

In [25]:
cols =['idx','id']
df[cols] = df[cols].astype('category')
df.dtypes

idx     category
id      category
name         str
dtype: object

In [26]:
df.head(2)

  idx   id name
0   1  444  abc
1   1  555  def

In [27]:
data = [[1,444,'abc'],
        [1,555,'def'],
        [3,666,'ghi'],
        [4,777,'xyz']
        ]
df =pd.DataFrame(data,columns=["idx","id","name"])
df.describe()

        idx          id
count  4.00    4.000000
mean   2.25  610.500000
std    1.50  143.300384
min    1.00  444.000000
25%    1.00  527.250000
50%    2.00  610.500000
75%    3.25  693.750000
max    4.00  777.000000

In [28]:
df['id'].nunique()

4

In [29]:
df.columns

Index(['idx', 'id', 'name'], dtype='str')

In [30]:
df['name'].idxmax()

3

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   idx     4 non-null      int64
 1   id      4 non-null      int64
 2   name    4 non-null      str
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [32]:
d = df['id'].value_counts()
d

id
444    1
555    1
666    1
777    1
Name: count, dtype: int64

In [33]:
df['id'].sum()

np.int64(2442)

In [34]:
df.max()

idx       4
id      777
name    xyz
dtype: object

In [35]:
df['id'].values

array([444, 555, 666, 777])

In [36]:
df.replace(666,"3939")

   idx    id name
0    1   444  abc
1    1   555  def
2    3  3939  ghi
3    4   777  xyz

In [37]:
df.replace({444:"Aya",777:444})

   idx   id name
0    1  Aya  abc
1    1  555  def
2    3  666  ghi
3    4  444  xyz

In [38]:
def duplicated(x):
    return x * 2


df['id'].apply(duplicated)

0     888
1    1110
2    1332
3    1554
Name: id, dtype: int64

In [39]:
df['id'].apply(lambda x : x*2)

0     888
1    1110
2    1332
3    1554
Name: id, dtype: int64

In [40]:
df.idx

0    1
1    1
2    3
3    4
Name: idx, dtype: int64

In [41]:
df.idx.iloc[2]

np.int64(3)

In [42]:
df.iloc[2,1]

np.int64(666)

In [43]:
df.iloc[:,0:2]

   idx   id
0    1  444
1    1  555
2    3  666
3    4  777

In [44]:
df["new_col"] = df.name + df.name
df

   idx   id name new_col
0    1  444  abc  abcabc
1    1  555  def  defdef
2    3  666  ghi  ghighi
3    4  777  xyz  xyzxyz

In [45]:
df=df.drop("new_col",axis=1)
df

   idx   id name
0    1  444  abc
1    1  555  def
2    3  666  ghi
3    4  777  xyz

In [46]:
# new_row ={"id":9,"idx":99,"name":"welcome"}
# df= pf.concat(df,pd.DataFrame)

In [47]:
null = df.isnull()
pd.DataFrame(null.sum()).T

   idx  id  name
0    0   0     0

In [48]:
def ck_null(df):
    return pd.DataFrame(null.sum()).T

In [49]:
df.dropna(subset=["idx"])

   idx   id name
0    1  444  abc
1    1  555  def
2    3  666  ghi
3    4  777  xyz

In [50]:
mean = df.id.mean()
df.name =df.name.fillna(value = mean)
# df